# Generated by Django 5.0 on 2023-12-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeParser', '0002_rename_candidate_name_jobmatch_candidate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
    ]
