# Generated by Django 5.0 on 2024-01-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeParser', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='candidate',
            field=models.IntegerField(null=True),
        ),
    ]
